### ISSUE TITLE
Infografia

### ISSUE THREAD

**Issue by DuilioAquino10** [SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-DuilioAquino10#1]
[Infografia RA.pdf](https://github.com/SistemasTecTlaxiaco/actividad-1-infografia-de-realidad-aumentada-DuilioAquino10/files/10809330/Infografia.RA.pdf)

**Comment by bg55-a** [comment]
Calificacion: 18

**Comment by josealfredo79** [comment]
Bien hecho y revisado
